version: '3'

services:
  srlab.mysql:
    image: mysql:8.0.18
    container_name: srlab-mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=tmd@123
      - MYSQL_DATABASE=tmdsr
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - srlab-net

  srlab.api:
    build: ./SpeedRunners.API/
    container_name: srlab-api
    restart: always
    ports:
      - "888:80"
    depends_on:
      - srlab.mysql
    networks:
      - srlab-net

  srlab.ui: 
    build: ./SpeedRunners.UI/
    container_name: srlab-ui
    volumes:
      - ./SpeedRunners.UI/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./SpeedRunners.UI/nginx/api.speedrunners.cn.pem:/etc/nginx/api.speedrunners.cn.pem
      - ./SpeedRunners.UI/nginx/api.speedrunners.cn.key:/etc/nginx/api.speedrunners.cn.key
    restart: always
    ports:
      - 80
      - 443
    depends_on:
      - srlab.api
    networks:
      - srlab-net

networks:
  srlab-net:
    driver: bridge