version: '3'

services:
  srlab.mysql:
    image: mysql:8.0.18
    container_name: srlab-mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=tmd@123
      - MYSQL_DATABASE=tmdsr
      - TZ=Asia/Shanghai
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - srlab-net

  srlab.api:
    build: ./SpeedRunners.API/
    container_name: srlab-api
    restart: always
    ports:
      - "888:80"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - srlab-net
    extra_hosts:
      - host.docker.internal:host-gateway

  srlab.ui: 
    build: ./SpeedRunners.UI/
    container_name: srlab-ui
    volumes:
      - ./SpeedRunners.UI/nginx:/etc/nginx/conf.d
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - srlab-net

  srlab.scheduler:
    build: ./SpeedRunners.Scheduler/
    container_name: srlab-scheduler
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      - srlab-net
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  srlab-net:
    driver: bridge